services:
  app:
    image: ghcr.io/lqvp/misskey-tools:master
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - YARN_NETWORK_TIMEOUT=300000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - TZ=Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json
      - ./migration:/app/migration
    restart: unless-stopped
    command: sh -c "yarn build:migrations && yarn migration:run && yarn start"
    networks:
      - default
      - db_network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tools
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tools"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db_network

networks:
  default:
    driver: bridge
  db_network:
    internal: true
